
site_name: "AI-Powered Blog"
site_description: "Automated content creation with cutting-edge AI"
author: "AI Blog System"
base_url: "https://yourusername.github.io/your-repo"
monetization_enabled: true
auto_posting: true
content_topics:
  - "artificial intelligence"
  - "machine learning"
  - "productivity"
  - "technology trends"
  - "digital marketing"
  - "automation"
  - "software development"
  - "data science"

# Note: API keys are loaded from environment variables for security
# Set OPENAI_API_KEY and GITHUB_TOKEN as environment variables or GitHub secrets
