
site_name: "AI-Powered Blog"
site_description: "Automated content creation with cutting-edge AI"
author: "AI Blog System"
base_url: "https://github.com/kubaik/AI_Blog_Publisher"
monetization_enabled: true
auto_posting: true
content_topics:
  - "artificial intelligence"
  - "machine learning"
  - "productivity"
  - "technology trends"
  - "digital marketing"
  - "automation"
  - "software development"
  - "data science"

