base_url: https://kubaik.github.io/ai-blog-system
base_path: /ai-blog-system  

content_topics:
- Machine Learning Algorithms
- Web Development Trends
- Data Science Techniques
- Artificial Intelligence Applications
- Cloud Computing Platforms
- Cybersecurity Best Practices
- Mobile App Development
- DevOps and CI/CD
- Database Optimization
- Frontend Frameworks
- Backend Architecture
- API Design Patterns
- Software Testing Strategies
- Performance Optimization
- Blockchain Technology
- Internet of Things (IoT)
- Microservices Architecture
- Container Technologies
- Serverless Computing
- Progressive Web Apps
site_description: Cutting-edge insights into technology, AI, and development
site_name: AI Tech Blog
